service: alex-personal-website-cloudfront

provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage}
  environment:
    CODE_BUCKET_NAME:
      Fn::ImportValue: Personal-Website-Code-Bucket
    PROJECT_DATA_BUCKET_NAME:
      Fn::ImportValue: Personal-Website-Project-Data-Bucket
  deploymentBucket:
    name: alex-personal-website-stack-bucket-np
  stackTags:
    application: "PersonalWebsite"
    owner: "Alex"

resources:
  Resources:
    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Fn::Join:
              - ''
              - - ${self:provider.environment.CODE_BUCKET_NAME}
                - '.s3.amazonaws.com'
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: index.html
          Origins:
            - DomainName:
                Fn::Join:
                  - ''
                  - - ${self:provider.environment.CODE_BUCKET_NAME}
                    - '.s3.amazonaws.com'
              Id: ${self:provider.environment.CODE_BUCKET_NAME}
              S3OriginConfig:
                OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
            - DomainName:
                Fn::Join:
                  - ''
                  - - ${self:provider.environment.PROJECT_DATA_BUCKET_NAME}
                    - '.s3.amazonaws.com'
              Id: ${self:provider.environment.PROJECT_DATA_BUCKET_NAME}
              S3OriginConfig:
                OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          DefaultCacheBehavior:
            TargetOriginId: ${self:provider.environment.CODE_BUCKET_NAME}
            ForwardedValues:
              Cookies:
                Forward: "none"
              QueryString: "true"
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - PUT
              - DELETE
              - PATCH
              - POST
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
        Tags:
          - Key: Environment
            Value: dev
          - Key: owner
            Value: Alex
          - Key: application
            Value: PersonalWebsite
    ResponseHeadersPolicy:
      Type: AWS::CloudFront::ResponseHeadersPolicy
      Properties: 
        ResponseHeadersPolicyConfig: 
          Name: personal-website-cloudfront-response-headers-policy-config-${self:provider.stage}
          CorsConfig: 
            AccessControlAllowCredentials: true
            AccessControlAllowHeaders: 
              Items: 
                - "Content-Type"
            AccessControlAllowMethods: 
              Items: 
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
                - OPTIONS
            AccessControlAllowOrigins:
              Items:
                - Fn::Join:
                  - ''
                  - - 'https://'
                    - !GetAtt CloudFrontDistribution.DomainName
            OriginOverride: false
    CodeBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:provider.environment.CODE_BUCKET_NAME}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                - !Sub
                  - "arn:aws:s3:::${CodeBucketName}/*"
                  - CodeBucketName: ${self:provider.environment.CODE_BUCKET_NAME}
              Principal:
                "AWS": !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            - Action:
                - "s3:DeleteBucketPolicy"
                - "s3:PutBucketPolicy"
              Effect: Deny
              Resource:
                - !Sub
                  - "arn:aws:s3:::${CodeBucketName}"
                  - CodeBucketName: ${self:provider.environment.CODE_BUCKET_NAME}
              Principal: "*"
              Condition:
                ArnNotEquals:
                  aws:PrincipalARN:
                    - !Sub "arn:aws:iam::${AWS::AccountId}:user/Alex"
            - Action:
                - "s3:PutObject*"
                - "s3:DeleteObject*"
              Effect: Deny
              Resource:
                - !Sub
                  - "arn:aws:s3:::${CodeBucketName}/*"
                  - CodeBucketName: ${self:provider.environment.CODE_BUCKET_NAME}
              Principal: "*"
              Condition:
                ArnNotEquals:
                  aws:PrincipalARN:
                    - !Sub "arn:aws:iam::${AWS::AccountId}:user/Alex"
    ProjectDataBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:provider.environment.PROJECT_DATA_BUCKET_NAME}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                - !Sub
                  - "arn:aws:s3:::${CodeBucketName}/*"
                  - CodeBucketName: ${self:provider.environment.PROJECT_DATA_BUCKET_NAME}
              Principal:
                "AWS": !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            - Action:
                - "s3:DeleteBucketPolicy"
                - "s3:PutBucketPolicy"
              Effect: Deny
              Resource:
                - !Sub
                  - "arn:aws:s3:::${CodeBucketName}"
                  - CodeBucketName: ${self:provider.environment.PROJECT_DATA_BUCKET_NAME}
              Principal: "*"
              Condition:
                ArnNotEquals:
                  aws:PrincipalARN:
                    - !Sub "arn:aws:iam::${AWS::AccountId}:user/Alex"
            - Action:
                - "s3:PutObject*"
                - "s3:DeleteObject*"
              Effect: Deny
              Resource:
                - !Sub
                  - "arn:aws:s3:::${CodeBucketName}/*"
                  - CodeBucketName: ${self:provider.environment.PROJECT_DATA_BUCKET_NAME}
              Principal: "*"
              Condition:
                ArnNotEquals:
                  aws:PrincipalARN:
                    - !Sub "arn:aws:iam::${AWS::AccountId}:user/Alex"

  Outputs:
    CloudFrontDistributionDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: personal-website-cloudfront-distribution-domain-name
    CloudFrontDistributionId:
      Value: !GetAtt CloudFrontDistribution.Id
      Export:
        Name: personal-website-cloudfront-distribution-id
